services:
  gotify:
    container_name: gotify
    restart: unless-stopped
    environment:
      - TZ=America/Denver
    volumes:
      - /opt/data/gotify:/app/data
    image: gotify/server
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.gotify.rule: Host(`${GOTIFY_HOST}`)
      traefik.http.routers.gotify.entrypoints: websecure
      traefik.http.routers.gotify.tls: true
      traefik.http.routers.gotify.tls.certresolver: le

network:
  proxy:
    external: true
