services:
  couchdb:
    image: apache/couchdb:3
    container_name: couchdb
    restart: unless-stopped

    env_file: .env

    volumes:
      - /opt/data/couchdb:/opt/couchdb/data

    networks:
      - proxy

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.couchdb.rule=Host(`${COUCHDB_HOST}`)"
      - "traefik.http.routers.couchdb.entrypoints=websecure"
      - "traefik.http.routers.couchdb.tls=true"
      - "traefik.http.routers.couchdb.tls.certresolver=le"
      - "traefik.http.services.couchdb.loadbalancer.server.port=5984"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
