services:

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: https://${VAULTWARDEN_DOMAIN}
      DISABLE_ADMIN_TOKEN: true
      SIGNUPS_ALLOWED: false
    volumes:
      - /opt/container-data/vaultwarden:/data/
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.vaultwarden.rule=Host(`${VAULTWARDEN_DOMAIN}`)
      - traefik.http.routers.vaultwarden.entrypoints=websecure
      - traefik.http.routers.vaultwarden.tls=true
      - traefik.http.routers.vaultwarden.tls.certresolver=le
      - traefik.http.routers.vaultwarden.service=vaultwarden
      - traefik.http.services.vaultwarden.loadbalancer.server.port=80
      - traefik.http.routers.vaultwarden-admin.rule=Host(`${VAULTWARDEN_DOMAIN}`) &&
        PathPrefix(`/admin`)
      - traefik.http.routers.vaultwarden-admin.entrypoints=websecure
      - traefik.http.routers.vaultwarden-admin.tls=true
      - traefik.http.routers.vaultwarden-admin.tls.certresolver=le
      - traefik.http.routers.vaultwarden-admin.middlewares=tinyauth@file
      - traefik.http.routers.vaultwarden-admin.service=vaultwarden
      - traefik.http.routers.vaultwarden-admin.priority=100
      
networks:
  proxy:
    external: true
