services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest-fat
    container_name: stirling-pdf
    volumes:
      - /opt/state/stirling/tessdata:/usr/share/tessdata
      - /opt/data/stirling/configs:/configs
      - /opt/state/stirling/logs:/logs
      - /opt/data/stirling/pipeline:/pipeline
    environment:
      - SECURITY_ENABLELOGIN=true
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.stirling.rule: Host(`${STIRLING_HOST}`)
      traefik.http.routers.stirling.entrypoints: websecure
      traefik.http.routers.stirling.tls: true
      traefik.http.routers.stirling.tls.certresolver: le
      traefik.http.services.stirling.loadbalancer.server.port: 8080
      traefik.docker.network: proxy
    networks:
      - proxy
      
networks:
  proxy:
    external: true
