services:

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
      - radicale-internal
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config/dynamic:/dynamic:ro
      - ./plugins/traefik-opencloud-user-mapper:/plugins-local/src/github.com/ryangladden/traefik-opencloud-user-mapper:ro
      - /opt/state/traefik/letsencrypt:/letsencrypt
      - /opt/state/traefik/certs:/certs
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test:
        - CMD
        - wget
        - --spider
        - -q
        - http://127.0.0.1:8080/ping
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 60s

networks:
  proxy:
    name: proxy
    external: true
  radicale-internal:
    external: true
