services:
  uptime-kuma:
    restart: always
    volumes:
      - /opt/data/uptime/:/app/data/
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: uptime-kuma
    image: louislam/uptime-kuma:2
    labels:
      traefik.enable: true
      traefik.http.routers.uptime.rule: Host(`uptime.gladden.uk`)
      traefik.http.routers.uptime.entrypoints: websecure
      traefik.http.routers.uptime.tls: true
      traefik.http.routers.uptime.tls.certresolver: le
    networks:
      - proxy
      
  # signal-cli-rest-api:
  #   container_name: signal-api
  #   image: bbernhard/signal-cli-rest-api:latest
  #   ports:
  #     - 8081:8080
  #   environment:
  #     - MODE=normal #supported modes: json-rpc, native, normal
  #     - AUTO_RECEIVE_SCHEDULE=0 22 * * * #enable this parameter on demand (see description below)
  #     - LOG_LEVEL=debug
  #   volumes:
  #     - /opt/data/uptime/signal-cli-config:/home/.local/share/signal-cli
  #   networks:
  #     - proxy
      
networks:
  proxy:
    external: true
