[[stack]]
name = "arr-stack"
[stack.config]
server = "gertrude"
linked_repo = "homelab"
run_directory = "services/arr-stack"
environment = """
SONARR_HOST=tv.[[HOST_DOMAIN]]
SONARR_USERNAME=[[ARR_USERNAME]]
SONARR_PASSWORD=[[ARR_PASSWORD]]

ANIME_HOST=anime.[[HOST_DOMAIN]]
ANIME_USERNAME=[[ARR_USERNAME]]
ANIME_PASSWORD=[[ARR_PASSWORD]]

RADARR_HOST=movies.[[HOST_DOMAIN]]
RADARR_USERNAME=[[ARR_USERNAME]]
RADARR_PASSWORD=[[ARR_PASSWORD]]

BAZARR_HOST=subtitles.[[HOST_DOMAIN]]
BAZARR_USERNAME=[[ARR_USERNAME]]
BAZARR_PASSWORD=[[ARR_PASSWORD]]

PROWLARR_HOST=index.[[HOST_DOMAIN]]
PROWLARR_USERNAME=[[ARR_USERNAME]]
PROWLARR_PASSWORD=[[ARR_PASSWORD]]

OVERSEERR_HOST=request.[[HOST_DOMAIN]]
OVERSEERR_USERNAME=[[ARR_USERNAME]]
OVERSEERR_PASSWORD=[[ARR_PASSWORD]]

QBITTORRENT_HOST=torrent.[[HOST_DOMAIN]]
QBITTORRENT_USERNAME=[[ARR_USERNAME]]
QBITTORRENT_PASSWORD=[[ARR_PASSWORD]]

PLEX_TOKEN=[[PLEX_TOKEN]]
PROTON_WIREGUARD_PRIVATE_KEY=[[PROTON_WIREGUARD_PRIVATE_KEY]]
"""
