[[stack]]
name = "homepage"
tags = ["service"]
[stack.config]
server = "gertrude"
linked_repo = "homelab"
run_directory = "services/homepage"
environment = """
HOMEPAGE_HOST=home.[[HOST_DOMAIN]]
HOMEPAGE_ALLOWED_HOSTS=home.[[HOST_DOMAIN]]
HOMEPAGE_VAR_HOST_DOMAIN=[[HOST_DOMAIN]]
HOMEPAGE_VAR_IMMICH_KEY=[[HOMEPAGE_IMMICH_API_KEY]]
"""
