[[stack]]
name = "lubelogger"
tags = ["service"]
[stack.config]
server = "gertrude"
linked_repo = "homelab"
run_directory = "services/lubelogger"
environment = """
LUBELOGGER_HOST=cars.[[HOST_DOMAIN]]
"""
