[[stack]]
name = "opencloud"
tags = ["service"]
[stack.config]
server = "gertrude"
linked_repo = "homelab"
run_directory = "services/opencloud"
environment = """
OC_DOCKER_TAG=7.4.0

LOG_LEVEL=debug
LOG_PRETTY=true

OC_OIDC_ISSUER=[[POCKETID_HOST]]
WEB_OIDC_CLIENT_ID=[[OPENCLOUD_CLIENT_ID]]
WEB_OIDC_AUTHORITY=[[OPENCLOUD_SECRET_ID]]
WEB_OIDC_METADATA_URL=[[POCKETID_HOST]]/.well-known/openid-configuration

OPENCLOUD_HOST=cloud.[[HOST_DOMAIN]]
OC_CONFIG_DIR=/opt/data/opencloud/config
OC_DATA_DIR=/opt/data/opencloud/data
OC_APPS_DIR=/opt/data/opencloud/app

INITIAL_ADMIN_PASSWORD=[[OPENCLOUD_ADMIN_PASSWORD]]

EURO_OFFICE_HOST=docs.[[HOST_DOMAIN]]
EURO_OFFICE_JWT_SECRET=[[EURO_OFFICE_JWT_SECRET]]

WOPISERVER_HOST=wopiserver.[[DOMAIN]]

DECOMPOSEDS3_ENDPOINT=[[S3_ENDPOINT]]
DECOMPOSEDS3_REGION=us-east-1
DECOMPOSEDS3_ACCESS_KEY=[[S3_ACCESS_KEY]]
DECOMPOSEDS3_SECRET_KEY=[[S3_SECRET_KEY]]
DECOMPOSEDS3_BUCKET=opencloud


SMTP_HOST=mail.[[HOST_DOMAIN]]
SMTP_PORT=587
SMTP_SENDER=no-reply@[[MAIL_DOMAIN]]
SMTP_USERNAME=no-reply@[[MAIL_DOMAIN]]
SMTP_PASSWORD=[[NO_REPLY_PASSWORD]]
SMTP_INSECURE=false
SMTP_AUTHENTICATION=plain
SMTP_ENCRYPTION=starttls
"""
