[[stack]]
name = "paperless-ngx"
tags = ["service"]
[stack.config]
server = "gertrude"
linked_repo = "homelab"
run_directory = "services/paperless-ngx"
environment = """
OMPOSE_PROJECT_NAME=paperless-ngx
PAPERLESS_OCR_LANGUAGES=eng por
PAPERLESS_ENABLE_ALLAUTH=true
PAPERLESS_APPS=allauth.socialaccount.providers.openid_connect
PAPERLESS_SOCIALACCOUNT_PROVIDERS={"openid_connect":{"SCOPE":["openid","profile","email"],"OAUTH_PKCE_ENABLED":true,"APPS":[{"provider_id":"pocket-id","name":"Pocket-ID","client_id":"[[PAPERLESS_CLIENT_ID]]","secret":"[[PAPERLESS_CLIENT_SECRET]]","settings":{"server_url":"https://[[POCKETID_HOST]]"}}]}}
#PAPERLESS_APPS=allauth.socialaccount.providers.openid_connect
#PAPERLESS_SOCIALACCOUNT_PROVIDERS={"openid_connect": {"APPS": [{"provider_id": "pocketid","name": "Pocket ID","client_id": "[[PAPERLESS_CLIENT_ID]]","secret": "[[PAPERLESS_CLIENT_SECRET]]","settings": {"server_url": "https://[[POCKETID_HOST]]/.well-known/openid-configuration","claims": {"username": "email"}}}],"OAUTH_PKCE_ENABLED": "True"}}
PAPERLESS_AUTO_LOGIN=true
PAPERLESS_AUTO_CREATE=true
PAPERLESS_LOGOUT_REDIRECT_URL="https://documents.[[HOST_DOMAIN]]/accounts/oidc/pocket-id/login/callback/"
PAPERLESS_URL=https://documents.[[HOST_DOMAIN]]
PAPERLESS_SECRET_KEY=[[PAPERLESS_SECRET_KEY]]
PAPERLESS_DISABLE_REGULAR_LOGIN=true
PAPERLESS_CONSUME_DIR=/usr/src/paperless/consume
PAPERLESS_HOST=documents.[[HOST_DOMAIN]]
"""
