[[stack]]
name = "searxng"
tags = ["service"]
[stack.config]
server = "gertrude"
linked_repo = "homelab"
run_directory = "services/searxng"
environment = """
TRAEFIK_SEARXNG_HOST=search.[[HOST_DOMAIN]]
SEARXNG_BASE_URL=https://search.[[HOST_DOMAIN]]
SEARXNG_SECRET=[[SEARXNG_SECRET]]
SEARXNG_VALKEY_URL=valkey://valkey:6379/0
"""
