[[stack]]
name = "tinyauth"
[stack.config]
server = "gertrude"
linked_repo = "homelab"
run_directory = "services/tinyauth"
environemnt = """
TINYAUTH_APPURL=https://[[TINYAUTH_HOST]]
TINYAUTH_AUTH_USERS=admin:[[TINYAUTH_ADMIN_PASS_HASH]]
TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTID=[[TINYAUTH_CLIENT_ID]]
TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTSECRET=[[TINYAUTH_CLIENT_SECRET]]
TINYAUTH_OAUTH_PROVIDERS_POCKETID_AUTHURL=https://[[POCKETID_HOST]]/authorize
TINYAUTH_OAUTH_PROVIDERS_POCKETID_TOKENURL=https://[[POCKETID_HOST]]/api/oidc/token
TINYAUTH_OAUTH_PROVIDERS_POCKETID_USERINFOURL=https://[[POCKETID_HOST]]/api/oidc/userinfo
TINYAUTH_OAUTH_PROVIDERS_POCKETID_REDIRECTURL=https://[[TINYAUTH_HOST]]/api/oauth/callback/pocketid
TINYAUTH_OAUTH_PROVIDERS_POCKETID_SCOPES=openid email profile groups
TINYAUTH_OAUTH_PROVIDERS_POCKETID_NAME=Pocket ID
TINYAUTH_OAUTH_AUTOREDIRECT=pocketid
TINYAUTH_HOST=[[TINYAUTH_HOST]]
"""
