[[stack]]
name = "traefik"
[stack.config]
server = "gertrude"
linked_repo = "homelab"
run_directory = "services/traefik"
environment = """
OC_MAPPER_USERNAME: [[OC_MAPPER_USERNAME]]
OC_MAPPER_APP_TOKEN: [[OC_MAPPER_APP_TOKEN]]
"""
