---
# Homepage - widgets.yaml
# Gertrude Homelab

- resources:
    label: Gertrude
    cpu: true
    memory: true
    disk: /
    uptime: true
    cputemp: true
    units: imperial
    refresh: 5000

- search:
    provider: duckduckgo
    focus: false
    showSearchSuggestions: true
    target: _blank

- datetime:
    text_size: xl
    format:
      dateStyle: medium
      timeStyle: short
      hourCycle: h24
