services:

  tinyauth:
    image: ghcr.io/steveiliop56/tinyauth:v5
    container_name: tinyauth
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.tinyauth.rule: Host(`${TINYAUTH_HOST}`)
      traefik.http.routers.tinyauth.entrypoints: websecure
      traefik.http.routers.tinyauth.tls: true
      traefik.http.routers.tinyauth.tls.certresolver: le
    networks:
      - proxy
      
networks:
  proxy:
    external: true
