directives:
  child-src:
    - '''self'''
  connect-src:
    - '''self'''
    - 'https://raw.githubusercontent.com/opencloud-eu/awesome-apps/'
    - 'https://${POCKETID_HOST}'
    - 'wss://${POCKETID_HOST}'
    - 'https://*.gladden.uk'
    - 'blob:'
    - 'data:'
    - 'https://cdn.emulatorjs.org/'
  default-src:
    - '''none'''
  font-src:
    - '''self'''
  frame-ancestors:
    - '''self'''
  frame-src:
    - '''self'''
    - "blob:"
    - 'https://embed.diagrams.net/'
    # In contrary to bash and docker the default is given after the | character
    - 'https://${EURO_OFFICE_DOMAIN}/'
    - 'https://docs.opencloud.eu'
    - 'https://*.${HOST_DOMAIN}'
  img-src:
    - '''self'''
    - 'data:'
    - 'blob:'
    - 'https://raw.githubusercontent.com/opencloud-eu/awesome-apps/'
    # In contrary to bash and docker the default is given after the | character
    - 'https://${EURO_OFFICE_DOMAIN}/'
    - 'https://docs.opencloud.eu'
    - 'https://*.${HOST_DOMAIN}'
  manifest-src:
    - '''self'''
  media-src:
    - '''self'''
  object-src:
    - '''self'''
    - 'blob:'
  script-src:
    - '''self'''
    - '''unsafe-inline'''
    - 'blob:'
    - "'unsafe-eval'"
  style-src:
    - '''self'''
    - '''unsafe-inline'''
  worker-src:
    - "'self'"
    - 'blob:'
