services:

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/container-data/traefik/config:/etc/traefik:ro
      - /opt/container-data/traefik/dynamic:/dynamic:ro
      - /opt/container-data/traefik/letsencrypt:/letsencrypt
      - /opt/container-data/traefik/certs:/certs
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test:
        - CMD
        - wget
        - --spider
        - -q
        - http://127.0.0.1:8080/ping
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 60s

networks:
  proxy:
    name: proxy
    external: true
