http:

  routers:

    gertrude:
      rule: "Host(`gertrude.{{ env "HOST_DOMAIN" }}`)"
      service: gertrude
      entrypoints:
        - websecure
      tls:
        certresolver: le
      middlewares:
        - tinyauth@file
        
    truenas:
      rule: "Host(`nas.{{ env "HOST_DOMAIN" }}`)"
      service: truenas
      entrypoints:
        - websecure
      tls:
        certresolver: le
      middlewares:
        - tinyauth@file

    dashboard:
      rule: Host(`dashboard.{{ env "HOST_DOMAIN" }}`)
      entryPoints:
        - websecure
      service: api@internal
      middlewares:
        - tinyauth@file
      tls:
        certResolver: le

    s3:
      rule: Host(`s3.{{ env "HOST_DOMAIN" }}`)
      entryPoints:
        - websecure
      service: s3
      tls:
        certResolver: le

    backrest:
      rule: Host(`backup.{{ env "HOST_DOMAIN" }}`)
      entryPoints:
        - websecure
      service: backrest
      middlewares:
        - tinyauth@file
      tls:
        certResolver: le

    printer:
      rule: Host(`printer.{{ env "HOST_DOMAIN" }}`)
      entryPoints:
        - websecure
      service: printer
      middlewares:
        - tinyauth@file
      tls:
        certResolver: le

  services:

    gertrude:
      loadBalancer:
        servers:
          - url: "http://{{ env "GERTRUDE_IP" }}:9090"

    truenas:
      loadBalancer:
        servers:
          - url: "http://{{ env "NAS_IP" }}"

    s3:
      loadBalancer:
        servers:
          - url: "http://{{ env "NAS_IP" }}:30293"

    backrest:
      loadBalancer:
        servers:
          - url: "http://{{ env "BACKUP_IP" }}:9898"

    printer:
      loadBalancer:
        servers:
          - url: "http://{{ env "PRINTER_IP" }}:80"

  middlewares:
    tinyauth:
      forwardauth:
        address: http://tinyauth:3000/api/auth/traefik
        authResponseHeaders:
          - Remote-User
          - Authorization
          
    opencloud-user-mapper:
      plugin:
        opencloud-user-mapper:
          opencloudURL: http://opencloud:9200
          usernameHeader: Remote-User
          outputHeader: X-Remote-User
          serviceUsernameEnv: OC_MAPPER_USERNAME
          appTokenEnv: OC_MAPPER_APP_TOKEN
          cacheTTL: 1h
          requestTimeout: 3s
